name: Actualizar IPTV TVPorInternet2

on:
  schedule:
    # Se ejecuta cada 25 minutos
    - cron: '*/25 * * * *'
  workflow_dispatch: # Botón manual

jobs:
  update:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: pip install requests

      - name: Correr script de actualización
        run: python update.py

      - name: Guardar cambios
        run: |
          git config --global user.name "IPTV Bot"
          git config --global user.email "bot@noreply.github.com"
          git add mi_lista_peru.m3u
          git commit -m "Auto-update: nuevos tokens" || exit 0
          git push
          
